# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=26)),
                ('counts', models.IntegerField()),
            ],
        ),
    ]
